### ISSUE TITLE
Setup DNS

### ISSUE THREAD

**Issue by gdams** [adoptium/blog.adoptium.net#12]
We are now ready to setup the DNS for the netlify app to point to blog.adoptium.net @chrisguindon please can you get this setup?

**Comment by chrisguindon** [comment]
blog.adoptium.net is now pointing to our Netlify servers:
http://blog.adoptium.net/

We are now waiting on DNS propagation so that Netlify can provision our Let’s Encrypt certificate. I would expect that to occur in the next 30 minutes or so.

**Comment by chrisguindon** [comment]
Actually, the cert was provision while I was typing my last comment!
