### ISSUE TITLE
Correctly use Gatsby Head API

### ISSUE THREAD

**Issue by LekoArts** [adoptium/blog.adoptium.net#219]
Switching from `react-helmet` to Gatsby Head API will require more work than changing the `<SEO />` component. As explained in the reference guide you'll need to add a `Head` **export** to any page that should have that data (https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/).

We have a guide on a SEO component here: https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-seo-component

Right now you have your metadata inside the body:

![Screenshot of chrome dev tools showing that meta tags are inside body](https://user-images.githubusercontent.com/16143594/203774270-6800f398-a53f-4bcc-b7a0-f0ee878465cb.png)

**Comment by gdams** [comment]
Thanks for your issue @LekoArts, I started doing this for our main website here https://github.com/adoptium/website-v2/pull/944 but at the time couldn't get it to work with my template files. I'll revisit this week.

**Comment by gdams** [comment]
It was to do with using the data from the GraphQL query but I've just realised I can use that in the same way with:

```js
export const Head = ({ data }) => {
  // do stuff with data here
  return (
    <Seo
      title={post.frontmatter.title}
      description={post.frontmatter.description || post.excerpt}
      twitterCard={twitterCard}
    />
  );
};
```

**Comment by gdams** [comment]
Thanks for your help @LekoArts, I appreciate you raising the issue here. We are moving all development into our main [website](https://github.com/adoptium/website-v2) going forwards (also written in Gatsby) and would love to talk to the Gatsby team at some point to make sure we're using all the usual best practices etc.
